name: Bygg og deploy
on:
    push:
        branches-ignore: # Kan legge til disse store feature branchene her
            - 'uttaksplanbuilder-rework'
        paths-ignore:
            # - '**.md'
            # - '**.MD'
            - '.gitignore'
            - '.editorconfig'
            - 'LICENCE'
            - 'CODEOWNERS'

jobs:
    build-app:
        name: Build
        uses: navikt/fp-gha-workflows/.github/workflows/build-app-frontend-pnpm.yml@main
        with:
            push-image: ${{ github.ref_name == 'master' }} # default: false
        secrets: inherit

    promote-foreldrepengeoversikt-dev:
        name: Deploy foreldrepengeoversikt til dev
        if: ${{ github.ref_name == 'master' }}
        needs: build-app
        uses: navikt/fp-gha-workflows/.github/workflows/deploy-app-pnpm.yml@main
        with:
            image: ghcr.io/${{ github.repository }}/foreldrepengeoversikt:${{ needs.build-app.outputs.build-version }}
            cluster: dev-gcp
            app: foreldrepengeoversikt
            namespace: po-familie-sommerstudenter-23
        secrets: inherit

    promote-svangerskapspengesoknad-dev:
        name: Deploy svangerskapspengesoknad til dev
        if: ${{ github.ref_name == 'master' }}
        needs: build-app
        uses: navikt/fp-gha-workflows/.github/workflows/deploy-app-pnpm.yml@main
        with:
            image: ghcr.io/${{ github.repository }}/svangerskapspengesoknad:${{ needs.build-app.outputs.build-version }}
            cluster: dev-gcp
            app: svangerskapspengesoknad
            namespace: po-familie-sommerstudenter-23
        secrets: inherit
