name: Bygg og deploy
on:
    push:
        branches-ignore: # Kan legge til disse store feature branchene her
            - 'uttaksplanbuilder-rework'
        paths-ignore:
            # - '**.md'
            # - '**.MD'
            - '.gitignore'
            - '.editorconfig'
            - 'LICENCE'
            - 'CODEOWNERS'

jobs:
    build-app:
        name: Build
        uses: navikt/fp-gha-workflows/.github/workflows/build-app-frontend-pnpm.yml@turborepo
        with:
            push-image: ${{ github.ref_name == 'master' }} # default: false
        secrets: inherit

    promote-foreldrepengesoknad:
        strategy:
            matrix:
                cluster: [ dev-gcp ]
        name: Deploy til ${{ matrix.cluster }}
        # environment: ${{ matrix.cluster }}:teamforeldrepenger
        needs: build-app
        uses: navikt/fp-gha-workflows/.github/workflows/deploy-app-pnpm.yml@turborepo
        with:
            image: ghcr.io/${{ github.repository }}/foreldrepengesoknad:${{ needs.build-app.outputs.build-version }}
            cluster: ${{ matrix.cluster }}}
        secrets: inherit
        
