name: "Deploy storybook"

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-storybook:
   uses: navikt/fp-gha-workflows/.github/workflows/deploy-storybook.yml@pnpm/storybook
   with:
     package-manager: pnpm
   secrets: inherit
